version: "3.7"

services:
  {{SERVICE.MEMORY_DATABASE.NAME}}:
    image: library/redis:6.0.6
    container_name: {{SERVICE.MEMORY_DATABASE.NAME}}
    hostname: memory.database.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - {{SERVICE.MEMORY_DATABASE.PORTS.PORT_EXPOSED}}:{{SERVICE.MEMORY_DATABASE.PORTS.PORT}}
    networks:
      - {{SERVICE.NETWORK.NAME}}

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true



